// Code generated by protoc-gen-go.
// source: main.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	main.proto

It has these top-level messages:
	TripleSet
	Triple
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type TripleSet struct {
	Triples []*Triple `protobuf:"bytes,1,rep,name=triples" json:"triples,omitempty"`
}

func (m *TripleSet) Reset()         { *m = TripleSet{} }
func (m *TripleSet) String() string { return proto.CompactTextString(m) }
func (*TripleSet) ProtoMessage()    {}

func (m *TripleSet) GetTriples() []*Triple {
	if m != nil {
		return m.Triples
	}
	return nil
}

type Triple struct {
	Subj string `protobuf:"bytes,1,opt,name=Subj" json:"Subj,omitempty"`
	Pred string `protobuf:"bytes,2,opt,name=Pred" json:"Pred,omitempty"`
	Obj  string `protobuf:"bytes,3,opt,name=Obj" json:"Obj,omitempty"`
}

func (m *Triple) Reset()         { *m = Triple{} }
func (m *Triple) String() string { return proto.CompactTextString(m) }
func (*Triple) ProtoMessage()    {}
